import React, {FC} from "react";

export const LoremIpsumParagraph: FC = () => {
    return (
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vitae eros dictum, condimentum orci nec, varius mi. Donec et fringilla nisl. Morbi a accumsan nisi, ut fermentum nulla. Donec vitae efficitur ipsum. Curabitur euismod, libero quis pretium scelerisque, mauris diam ullamcorper metus, scelerisque maximus diam velit eget sem. Nunc ut dolor et odio convallis varius ut at velit. Nullam a dictum mauris, non aliquet ante.

            In hac habitasse platea dictumst. Integer congue, enim vitae facilisis consectetur, ipsum purus condimentum tortor, eu sollicitudin lacus magna id purus. Duis sagittis turpis id mi consequat, consectetur consectetur ligula consequat. In enim arcu, malesuada eu magna vel, condimentum placerat dolor. Nunc faucibus feugiat porttitor. Proin mattis arcu eget tempus hendrerit. Morbi eu urna interdum, fringilla dolor quis, porttitor magna. Nunc rhoncus ex massa, a rhoncus lacus imperdiet fermentum. Donec elementum est turpis, sed condimentum purus aliquet pharetra.

            Ut vehicula condimentum enim, scelerisque volutpat nibh facilisis mattis. Mauris vulputate lectus eu ultrices eleifend. Nunc porta libero leo, ac dapibus lorem pulvinar ut. Integer lectus est, varius et dolor in, vulputate convallis velit. Sed ac luctus elit. Aenean a gravida est, ac tempus turpis. Duis porttitor sed augue eget aliquam. Integer lobortis suscipit dui a maximus. Aliquam porta, libero in posuere rutrum, lorem augue egestas nisl, nec scelerisque lacus sapien sit amet purus. Fusce in finibus nulla. Vivamus nibh nisl, iaculis laoreet magna non, convallis lobortis augue. Suspendisse potenti. Nunc nulla purus, vulputate et mi a, luctus fringilla nulla. Donec sollicitudin purus sem. Nunc eu porttitor urna. Donec euismod luctus ex ut eleifend.

            Etiam tellus nulla, porttitor sagittis facilisis eu, aliquam nec odio. Integer pharetra ligula a elementum convallis. In et condimentum metus. Vestibulum vel nibh eget magna congue volutpat. Mauris et elit est. Duis ultrices eu nisi quis euismod. Phasellus quis tortor interdum, dignissim orci fermentum, sagittis augue. Curabitur sit amet viverra mauris, a pretium ipsum. Ut tristique, lacus vitae imperdiet dictum, ipsum nibh molestie leo, eu cursus ante elit quis velit. Etiam sollicitudin mi at ex maximus, eget auctor diam aliquam. Pellentesque tincidunt vehicula finibus. Maecenas at risus sed ligula tempor mollis. In viverra nisl quis nisi posuere, in volutpat orci tristique. Curabitur condimentum porttitor vulputate.

            Nullam nec sodales nisl, et lacinia ipsum. Curabitur non purus eleifend, porttitor quam a, pellentesque magna. Suspendisse et tellus eget urna lobortis cursus. Sed ut justo ultricies enim viverra eleifend ut eget sem. Donec laoreet eros sit amet magna cursus dignissim. Nulla urna ex, sodales ut ipsum sit amet, pellentesque mollis orci. Sed non velit tristique, porta purus non, consectetur velit. Vivamus vestibulum eros ut eros malesuada, eget sollicitudin enim pulvinar. Aliquam porta nisi sed felis dapibus, pellentesque laoreet velit porta. Ut ut aliquet leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed at turpis ut leo volutpat convallis. Sed mollis elit libero, ac varius nisi rutrum et. Sed odio dolor, rutrum vel metus ut, fringilla feugiat tellus. Suspendisse nisi nisi, fringilla ut gravida sit amet, mollis id dolor. Suspendisse vel suscipit nibh, in iaculis augue.
        </p>
    )
}